### ISSUE TITLE
Submit a pull request to my repo

### ISSUE THREAD

**Issue by NoahCristino** [dogesum/robloxlib#1]
Now that people are interested I'll continue to work on this. Submit a pull request and I'll add your code!

**Comment by NoahCristino** [comment]
Copy your code you added. Delete this repo. Then fork mine, paste your code into the main file and submit a pull req and i'll accept it.

**Comment by dogesum** [comment]
I will do that soon, I am on my phone at the moment.

**Comment by NoahCristino** [comment]
@dogesum I added your changes just delete this repo and fork mine so you can make changes and submit pull requests (you can't right now because you just copied the code rather than forking)

**Comment by dogesum** [comment]
Thanks for already copying the stuff over, I will fork yours to make changes from now on.
